name: 📋 Task
description: Create a new task
title: "[TASK] <title>"
labels: ["Task", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the task you want to create.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: What's expected
    description: A clear description of what needs to be accomplished.
    placeholder: |
      Describe the task objective and deliverables...
  validations:
    required: true
- type: textarea
  attributes:
    label: Reference
    description: Links to related documents, designs, specifications, or other issues.
    placeholder: |
      - Design: [link]
      - Specification: [link]
      - Related issue: #123
  validations:
    required: false
- type: textarea
  attributes:
    label: Acceptance Criteria
    description: List the specific conditions that must be met for this task to be considered complete.
    placeholder: |
      - Criteria 1
      - Criteria 2
      - Criteria 3
  validations:
    required: true
