import type { Movie } from "./types";
export const movies: Movie[] = [
  { title: "Superboys of Malegaon", year: 2024, director: "Reema Kagti", genre: ["Biography", "Comedy", "Drama"], image: "https://m.media-amazon.com/images/M/MV5BYmJjZGFkMzktMjAxZC00ZTNiLTljMzItYzVjMTcyYWNiYWNkXkEyXkFqcGc@._V1_FMjpg_UY3000_.jpg", recent: true },
  { title: "War Dogs", year: 2016, genre: ["Comedy", "Crime", "Drama"] },
  { title: "Ready Player One", year: 2018, genre: ["Sci-Fi", "Action", "Adventure"] },
  { title: "Interstellar", year: 2014, genre: ["Sci-Fi", "Adventure", "Drama"] },
  { title: "Top Gun: Maverick", year: 2022, genre: ["Action", "Drama"] },
  { title: "Yesterday", year: 2019, genre: ["Comedy", "Music", "Fantasy"] },
  { title: "Edge of Tomorrow", year: 2014, genre: ["Action", "Sci-Fi"] },
  { title: "Spider-Man: No Way Home", year: 2021, genre: ["Action", "Adventure", "Fantasy"] },
  { title: "Ad Astra", year: 2019, genre: ["Sci-Fi", "Adventure", "Drama"] },
  { title: "Godzilla Minus One", year: 2023, genre: ["Action", "Adventure", "Drama"] },
  { title: "The Big Short", year: 2015, genre: ["Biography", "Comedy", "Drama"] },
  { title: "Article 370", year: 2023, genre: ["Drama", "Thriller"] },
  { title: "Maharaja", year: 2023, genre: ["Action", "Drama"] },
  { title: "The Truman Show", year: 1998, genre: ["Comedy", "Drama"] },
  { title: "Moneyball", year: 2011, genre: ["Biography", "Drama", "Sport"] },
  { title: "Oppenheimer", year: 2023, genre: ["Biography", "Drama", "History"] },
  { title: "The Prestige", year: 2006, genre: ["Drama", "Mystery", "Sci-Fi"] },
  { title: "The Intern", year: 2015, genre: ["Comedy", "Drama"] },
  { title: "Se7en", year: 1995, genre: ["Crime", "Drama", "Mystery"] },
  { title: "Laapataa Ladies", year: 2023, genre: ["Comedy", "Drama"] },
  { title: "Badla", year: 2019, genre: ["Crime", "Drama", "Mystery"] },
  { title: "Inglourious Basterds", year: 2009, genre: ["Adventure", "Drama", "War"] },
  { title: "Air", year: 2023, genre: ["Drama", "Sport"] },
  { title: "The Green Mile", year: 1999, genre: ["Crime", "Drama", "Fantasy"] },
];
